modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "biotech"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[mixins]]
config = "biotech.mixins.json"

[[dependencies.biotech]]
    modId = "neoforge"
    type = "required"
    versionRange = "${neo_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.biotech]]
    modId = "minecraft"
    type = "required"
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"